### ISSUE TITLE
Yet the problem with named instances in "New-PSDCClone" is not solved.

### ISSUE THREAD

**Issue by ChebotovViktor** [sqlcollaborative/PSDatabaseClone#59]
If run "**New-PSDCClone -SQLinstance Server01\istance01**" then error: [New-PSDCClone] Couldn't connect to host remotely. Verify that the specified computer name is valid, that the computer is accessible over the network, and that a firewall exception for the WinRM service is enabled and allows access from this computer

**Comment by sanderstad** [comment]
For me to be able to help you I need more information. 
Is the command run locally or remotely?

**Local**
If this is local, is this really the name of the instance because I see some irregularities in the name. This may be a typo in the issue but want to be sure we're on the same page.

Make sure that when you use a named instance, you should put the name if the instance between quotes due to the "\". I see the name of the named instance is "istance01". Maybe that's a typo.

What happens when you run this:
`New-PSDCClone -SQLinstance "Server01\instance01"`

**Remotely**
If this is execute to create the clone than you need to be sure PS Remoting is enabled. Without it, the command will not be able to execute.

To test if PS Remoting is enabled correctly you can run something like this

```
$computername = "yourcomputername"
$result = Invoke-Command -ComputerName $computername { 1 } 

if($result -ne 1) 
{ 
    Write-Host "Remoting to $computerName returned an unexpected result." 
} 
```
This example is from Lee Holmes's blog [post](https://www.leeholmes.com/blog/2009/11/20/testing-for-powershell-remoting-test-psremoting/).

**Comment by sanderstad** [comment]
I have made several changes and pushed to the development branch. 
I have not been able to create a well enough test environment to get the same kind of errors.
If you could test it from the development branch and tell me if you still have the problem, that would be great.
